TOPDIR ?= ../..
include $(TOPDIR)/.config

$(CLIMATE_RECEIVER_SUPPORT)_SRC += services/climatereceiver/climatercv.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
# 
