TOPDIR ?= ../..
include $(TOPDIR)/.config

$(CLIMATE_RECORDER_SUPPORT)_SRC += services/climaterecorder/climate.c
$(CLIMATE_RECORDER_SUPPORT)_ECMD_SRC += services/climaterecorder/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
# 