TOPDIR ?= ../..
include $(TOPDIR)/.config

$(DEBUG_CLIMATE_RECORDER)_SRC += services/climaterecorder/climate.c
$(DEBUG_CLIMATE_RECORDER)_ECMD_SRC += services/climaterecorder/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
# 