TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(RFM69_SUPPORT)_SRC += hardware/radio/rfm69/rfm69.c



##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk


