TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FILE_LOGGER_SUPPORT)_SRC += services/climatelogger/filelogger.c
$(FILE_LOGGER_SUPPORT)_ECMD_SRC += services/climatelogger/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
