TOPDIR ?= ../..
include $(TOPDIR)/.config

$(RFM69_RECEIVER_SUPPORT)_SRC += services/rfm69receiver/rfm69receiver.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
# 
